name: Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      version-raw:
        type: string
      no-suffix:
        type: boolean
        default: false

        
defaults:
  run:
    shell: pwsh

env:
  DOTNET_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  NUGET_PACKAGES: ${{github.workspace}}/artifacts/pkg

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ${{ inputs.version-raw && format('#{0}', inputs.version-raw) || '' }}
    env:
      VersionSuffix: ${{ !inputs.no-suffix && inputs.version }}
      DoNotAddSuffix: ${{ inputs.no-suffix && '1' }}
      ContinuousIntegrationBuild: true
    steps:
    - name: Configure git
      run: |
        git config --global core.autocrlf input

    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true
        submodules: recursive

    # TODO: maybe we can eventually use package locks for package caching?
    
    - name: Install .NET SDK
      uses: nike4613/install-dotnet@533307d1c90c37993c8ef1397388bc9783e7b87c
      with:
        global-json: global.json
        
    # NOTE: manual package caching
    - name: Cache restored NuGet packages
      uses: actions/cache@v4
      with:
        path: ${{ env.NUGET_PACKAGES }}
        key: ${{ runner.os }}-nuget-v1-${{ hashFiles('**/*.csproj', '**/*.props', '**/*.targets', 'nuget.config', 'global.json') }}
        restore-keys: ${{ runner.os }}-nuget-v1-

    - name: Restore
      run: dotnet restore -bl:restore.binlog -noAutoRsp

    - name: Build
      run: dotnet build --no-restore -c Release -bl:build.binlog -clp:NoSummary -noAutoRsp

    - name: Pack
      run: dotnet pack --no-restore -c Release -bl:pack.binlog -clp:NoSummary -noAutoRsp


    # TODO: if/when we add tests, run them here and hook up test reporting
    #- name: Run auxiliary tests
    #  run: dotnet test --no-build -c Release -l:"trx;LogFileName=$($env:LOG_FILE_NAME)"
    #
    #- name: Upload test results
    #  uses: actions/upload-artifact@v4
    #  if: ${{ always() }}
    #  with:
    #    name: test-results aux ${{ runner.os }}
    #    retention-days: 1
    #    path: 'TestResults/*.trx'
    #    if-no-files-found: ignore

    - name: Upload binlogs
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: binlogs-${{ runner.os }}
        path: '*.binlog'
        retention-days: 7

    - name: Archive packages
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: artifacts/package/release/*.nupkg
